// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr9iOJ3B6s5cM3RXuf-KPODdHb_SWifD4',
    appId: '1:950203864393:web:ec0cde3b33a2b9cd3af698',
    messagingSenderId: '950203864393',
    projectId: 'fir-app-cd159',
    authDomain: 'fir-app-cd159.firebaseapp.com',
    storageBucket: 'fir-app-cd159.appspot.com',
    measurementId: 'G-WJGP4GYDXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdC6K8JTCJW0aKARUrN9LtRvXDtoldTP0',
    appId: '1:950203864393:android:b8d1813dc3658dc13af698',
    messagingSenderId: '950203864393',
    projectId: 'fir-app-cd159',
    storageBucket: 'fir-app-cd159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4Jlzeq-KBOfkkGVPWFtNT7sLmxLuGDs',
    appId: '1:950203864393:ios:e1754f9abd94055e3af698',
    messagingSenderId: '950203864393',
    projectId: 'fir-app-cd159',
    storageBucket: 'fir-app-cd159.appspot.com',
    androidClientId: '950203864393-570rc8o6evus12spllmc8oregct9u9c3.apps.googleusercontent.com',
    iosClientId: '950203864393-vql4rvmsgsamu06paofovs6c814cet3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.artistCommunityUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4Jlzeq-KBOfkkGVPWFtNT7sLmxLuGDs',
    appId: '1:950203864393:ios:806fa778f366482e3af698',
    messagingSenderId: '950203864393',
    projectId: 'fir-app-cd159',
    storageBucket: 'fir-app-cd159.appspot.com',
    androidClientId: '950203864393-570rc8o6evus12spllmc8oregct9u9c3.apps.googleusercontent.com',
    iosClientId: '950203864393-13lsfi5idoki28ih21u0i6e1iib0ta4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.artistCommunityUser.RunnerTests',
  );
}
